# Generated by Django 2.2.6 on 2019-10-23 22:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('minute', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('journey', models.IntegerField(validators=[django.core.validators.MaxValueValidator(34), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='KindEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('address', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('number_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('foundation_date', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('stadium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page.Stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('nick', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Team')),
            ],
        ),
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shots', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ball_possession', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('corners', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Stadium'),
        ),
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ManyToManyField(through='page.GameStatus', to='page.Team'),
        ),
        migrations.CreateModel(
            name='PlayerPlayGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ManyToManyField(to='page.Event')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Player')),
            ],
            options={
                'unique_together': {('player', 'game')},
            },
        ),
    ]
